//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.29 at 12:49:40 PM CEST 
//


package fr.fayss.datagenerator.atg.gsa;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.fayss.datagenerator.atg.gsa package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PropertyConfigDataGeneratorRef_QNAME = new QName("", "dataGeneratorRef");
    private final static QName _PropertyConfigPropertyConfig_QNAME = new QName("", "propertyConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.fayss.datagenerator.atg.gsa
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dataconfig }
     * 
     */
    public Dataconfig createDataconfig() {
        return new Dataconfig();
    }

    /**
     * Create an instance of {@link Dataconfig.MainGenerators }
     * 
     */
    public Dataconfig.MainGenerators createDataconfigMainGenerators() {
        return new Dataconfig.MainGenerators();
    }

    /**
     * Create an instance of {@link Dataconfig.DataGenerator }
     * 
     */
    public Dataconfig.DataGenerator createDataconfigDataGenerator() {
        return new Dataconfig.DataGenerator();
    }

    /**
     * Create an instance of {@link PropertyConfig }
     * 
     */
    public PropertyConfig createPropertyConfig() {
        return new PropertyConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataGeneratorRef", scope = PropertyConfig.class)
    public JAXBElement<String> createPropertyConfigDataGeneratorRef(String value) {
        return new JAXBElement<String>(_PropertyConfigDataGeneratorRef_QNAME, String.class, PropertyConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "propertyConfig", scope = PropertyConfig.class)
    public JAXBElement<PropertyConfig> createPropertyConfigPropertyConfig(PropertyConfig value) {
        return new JAXBElement<PropertyConfig>(_PropertyConfigPropertyConfig_QNAME, PropertyConfig.class, PropertyConfig.class, value);
    }

}
